version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    container_name: "mysqldb"
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    volumes:
      - ./volumes/database:/var/lib/mysql

  app_posts_api:
    depends_on:
      - mysqldb
    build: ./posts-api
    container_name: "app_posts_api"
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_POSTS_API_PORT:$NODE_POSTS_API_PORT
    expose:
      - $NODE_POSTS_API_PORT
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_PORT=$MYSQL_PORT
      - NODE_POSTS_API_PORT=$NODE_POSTS_API_PORT
      - NODE_APP_HOST=$NODE_APP_HOST
      - NODE_ENV=$NODE_ENV
    stdin_open: true
    tty: true
